AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create EC2 and RDS instances with tags

Parameters:
  EC2InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref EC2InstanceType
      KeyName: demo-key  # Replace with your Keypair
      ImageId: ami-0c42696027a8ede58  # Replace with your desired AMI ID
      SecurityGroups:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: auto-stop
          Value: true

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Security Group
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp

  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: adminpassword
      DBName: mydatabase
      MultiAZ: false
      Tags:
        - Key: auto-stop
          Value: true

Outputs:
  EC2InstancePublicDNS:
    Description: Public DNS of the EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName

  RDSInstanceEndpoint:
    Description: RDS instance endpoint
    Value: !GetAtt MyDBInstance.Endpoint.Address
